import { generateDynamicFAQs } from '@/lib/seo/contentEngine';
import { Card } from '@/components/ui/Card';

/**
 * Visible FAQ for the programmatic calculator pages.
 *
 * Deliberately emits no FAQPage JSON-LD. These questions are generated by
 * substituting a number into a fixed template — "Werden bei 100 Tagen auch
 * Wochenenden mitgezählt?" differs from the 90-day page only in the numeral.
 * Marking up hundreds of pages with structurally identical Q&A is exactly the
 * mass-duplication that structured data is not for, and it would be asserting
 * distinctness the content does not have.
 *
 * It also buys nothing: FAQ rich results are limited to well-known
 * authoritative government and health sites, so this markup earns no SERP
 * feature on a calculator page. Removing it costs no visibility and removes a
 * duplication signal.
 *
 * FAQPage markup is retained where the questions are written per page rather
 * than generated: the homepage and the four tool hubs.
 */
export function FAQBlock({ intent, slug, locale }: { intent: string; slug: string; locale: string }) {
    const match = slug.match(/^(\d+)-/);
    const numValue = match ? parseInt(match[1]) : undefined;
    const faqs = generateDynamicFAQs(intent, slug, locale, numValue);

    return (
        <Card as="section">
            <h2 className="text-2xl font-bold mb-8 text-ink">
                {locale === 'de' ? 'Häufig gestellte Fragen (FAQ)' : 'Frequently Asked Questions (FAQ)'}
            </h2>

            <div className="space-y-6">
                {faqs.map((faq, index) => (
                    <div key={index} className="space-y-2 pb-6 border-b border-line last:border-0 last:pb-0">
                        <h3 className="text-lg font-semibold text-ink">{faq.question}</h3>
                        <p className="text-ink-2 leading-relaxed">{faq.answer}</p>
                    </div>
                ))}
            </div>
        </Card>
    );
}
